# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

min_gower_rcpp <- function(data1_r, data2_r, n_threads = 0L) {
    .Call(`_flexsdm_min_gower_rcpp`, data1_r, data2_r, n_threads)
}

min_gower_parallel <- function(data1_r, data2_r, n_threads = 0L) {
    .Call(`_flexsdm_min_gower_parallel`, data1_r, data2_r, n_threads)
}

