# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euc_dist <- function(x, y) {
    .Call(`_flexsdm_euc_dist`, x, y)
}

euc_dist_min <- function(x, y) {
    .Call(`_flexsdm_euc_dist_min`, x, y)
}

mah_dist <- function(x, y, cov) {
    .Call(`_flexsdm_mah_dist`, x, y, cov)
}

mah_dist_min <- function(x, y, cov) {
    .Call(`_flexsdm_mah_dist_min`, x, y, cov)
}

min_gower_rcpp <- function(data1_r, data2_r, n_threads = 0L) {
    .Call(`_flexsdm_min_gower_rcpp`, data1_r, data2_r, n_threads)
}

